/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ee48896e-a376-448b-a1ad-c83f0ad53eae",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Dh3gXBjxJ",
    "aws_user_pools_web_client_id": "5ra3lanrsbe6lq0uq3mi861esc",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://h3bsxlgkjnerfkp3sjrxqsj7e4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fsa6jh53evgxjooo6ohiktkms4",
    "aws_user_files_s3_bucket": "weatherapp4thisbucket102107-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
