/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://h3bsxlgkjnerfkp3sjrxqsj7e4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fsa6jh53evgxjooo6ohiktkms4",
    "aws_user_files_s3_bucket": "weatherapp4thisbucket102107-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
